# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/TaeGeuni"

[social.params]
icon = "brand-github"

[[social]]
identifier = "email"
name = "Email"
url = "#" 

[social.params]
icon = "mail"
clipboard = "qoxorms1504@gmail.com"